# 总文件
lingDream:
  controller:
    listPage: admin/index/list
    insertPage: admin/index/insert
    resultPage: admin/adminPublic/addResult
    aspect: true
  service:
    aspect:
      update: true
      insert: true
#SpringBoot 的总配置文件

#激活开发环境
#
spring:
  profiles:
    active: dev

#激活测试环境
#spring.profiles.active=test

#激活生产环境
#spring:
#  profiles:
#    active: product

